version: '2'
services:
  web:
    build:
      context: ../
      dockerfile: docker/images/Node/Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
  mongodb:
    build:
      context: ../
      dockerfile: docker/images/Mongo/Dockerfile
    ports:
      - "27017:27017"
